apiVersion: v1
kind: Service
metadata:
  name: productmanagement-api-service
  namespace: productmanagement
  labels:
    app: productmanagement-api
spec:
  type: LoadBalancer  # For Minikube: minikube tunnel
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: productmanagement-api