apiVersion: v1
kind: ConfigMap
metadata:
  name: productmanagement-config
  namespace: productmanagement
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  JwtSettings__Issuer: "ProductManagementAPI"
  JwtSettings__Audience: "ProductManagementClient"
  JwtSettings__AccessTokenExpirationMinutes: "60"
  JwtSettings__RefreshTokenExpirationDays: "7"