apiVersion: v1
kind: Secret
metadata:
  name: productmanagement-secret
  namespace: productmanagement
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver-service;Database=ProductManagementDB;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;MultipleActiveResultSets=true"
  ConnectionStrings__Redis: "redis-service:6379"
  JwtSettings__SecretKey: "YourSuperSecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm!"
  SQL_SA_PASSWORD: "YourStrong@Password123"